default: &default
  adapter: postgresql
  encoding: unicode
  host: ''
  username: stanislaw
  password:
  pool: 5

development:
  <<: *default
  database: mydb


test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  pool: 5
  timeout: 5000