default: &default
  adapter: postgresql
  encoding: unicode
  host: ''
  username: stanislaw
  password:
  pool: 5

development:
  <<: *default
  database: mydb


test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  database: myapp_production
  username: kinoportalby
  password: <%= ENV['KINOPORTALBY_PASSWORD'] %>