default: &default
  adapter: postgresql
  encoding: unicode
  host: ''
  pool: 5

development:
  <<: *default
  database: mydb


test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production